server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://knlyuacbcpjwkc:1fc2e48404ab6e00e1837262acc01f01ef67100324197b97c46b6dc79be37d1d@ec2-54-243-92-68.compute-1.amazonaws.com:5432/d9odrphemcori7
    username: knlyuacbcpjwkc
    password: 1fc2e48404ab6e00e1837262acc01f01ef67100324197b97c46b6dc79be37d1d
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp Santander - DIO / Java Backend